### ISSUE TITLE
Project not found

### ISSUE THREAD

**Issue by DumoulinPierre** [bjorg/RadiantPi.Trinnov.Altitude#2]
Hi,

I wanted to use your new project, but the cmd " dotnet add package RadiantPi.Trinnov.Altitude" not works on my raspberry pi (sorry french error) :

```
Projet introuvable dans '/home/pi/projects/RadiantPi.Trinnov.Altitude/'.
Utilisation : dotnet add <PROJECT> package [options] <PACKAGE_NAME>
```

I also tried 
```
dotnet add Source/RadiantPi.Trinnov.Altitude/RadiantPi.Trinnov.Altitude.csproj package RadiantPi.Trinnov.Altitude
```

but end with "error: Value cannot be null. (Parameter 'path1')" 

Thanks a lot,
Pierre.

**Comment by bjorg** [comment]
Closing due to lack of response.
